version: "3.5"

services:

  # https://hub.docker.com/_/mariadb | https://hub.docker.com/_/mysql/
  db:
    image: ${DB_IMAGE}:${DB_VERSION}
    container_name: ${PROJECT_NAME}-db
    # Quit error message of mysql log: "mbind: Operation not permitted"
    cap_add:
      - SYS_NICE
    restart: ${RESTART}
    user: "${USER_ID}:${GROUP_ID}"
    environment:
      # - MYSQL_ROOT_HOST="%" # Apple M1 compatibility
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      # - ${DOCKER_PATH}/db/config:/etc/mysql/conf.d
      - ${DOCKER_PATH}/db/data:/var/lib/mysql:delegated
      - ${DOCKER_PATH}/db/init-db/:/docker-entrypoint-initdb.d
    # platform: linux/amd64 # Apple M1 compatibility
    ports:
      - "${DB_IP}:${DB_PORT}:3306"
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=${DB_CHARSET}',
      '--collation-server=${DB_COLLATE}'
    ]
    networks:
      - wordpress

  # Use the PHP image (not WordPress image)
  wordpress:
    depends_on:
      - db
    container_name: ${PROJECT_NAME}-wordpress
    build:
      context: ${DOCKER_PATH}/wp
      args:
        - version=${PHP_VERSION}
        - uid=${USER_ID}
        - gid=${GROUP_ID}
    restart: ${RESTART}
    volumes:
      - ${WP_LOCAL_HOME}:/var/www/html
      - ${DOCKER_PATH}/wp/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - wordpress


  # https://hub.docker.com/_/nginx
  nginx:
    depends_on:
      - wordpress
    image: nginx:1
    container_name: ${PROJECT_NAME}-nginx
    restart: ${RESTART}
    environment:
      - "DOMAIN=${DOMAIN}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${WP_LOCAL_HOME}:/var/www/html:rw,cached
      - ${DOCKER_PATH}/nginx/conf/:/etc/nginx/templates/
      - ${DOCKER_PATH}/nginx/ssl/:/etc/ssl/:ro
      - ${DOCKER_PATH}/logs/access.log:/var/log/nginx/access.log
      - ${DOCKER_PATH}/logs/error.log:/var/log/nginx/error.log
    networks:
      wordpress:
        # Fix cURL error
        aliases:
          - ${DOMAIN}


  # http://localhost:<PHPMYADMIN_PORT>
  # https://hub.docker.com/_/phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: ${PROJECT_NAME}-phpmyadmin
    restart: ${RESTART}
    environment:
      # Service name
      PMA_HOST: db
      UPLOAD_LIMIT: 128M
    ports:
      - "${DB_IP}:${PHPMYADMIN_PORT}:80"
    networks:
      - wordpress

  # All mail sent from this environment will be captured in MailHog and can be viewed in:
  # http://localhost:8025/
  # mailhog:
  #   container_name: ${PROJECT_NAME}-mailhog
  #   image: mailhog/mailhog
  #   ports:
  #     - "8025:8025"
  #     - "1025:1025"
  #   networks:
  #     - wordpress


networks:
  wordpress:
    name: ${PROJECT_NAME}-wordpress
    driver: bridge
